matrix:
  include:
    - sudo: required
      language: java
      dist: trusty
      jdk:
        - openjdk11

      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;

    - os: windows
      language: generic
      before_script:
        - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install openjdk ; fi
        - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install maven ; fi
  
script:
  - MAVEN_OPTS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
  - mvn clean install

after_failure:
 - find ./ -type d -name "surefire-reports" -print0 | xargs -0 -I {} find {} -iname "*.txt" -type f | xargs cat
 - find . -type f -name "*.log" -print0 -exec cat {} \;
