jobs:
  include:
    - sudo: required
      language: java
      dist: trusty
      jdk:
        - openjdk11

      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;

    - os: windows
      language: bash
      before_script:
        - choco install openjdk11 -ia INSTALLDIR="c:\jdk"
        - choco install maven -ia INSTALLDIR="c:\mvn"
        - export PATH=$PATH:"/c/jdk":"/c/mvn"
  
script:
  - MAVEN_OPTS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
  - echo ${PATH}
  - mvn clean install

after_failure:
 - find ./ -type d -name "surefire-reports" -print0 | xargs -0 -I {} find {} -iname "*.txt" -type f | xargs cat
 - find . -type f -name "*.log" -print0 -exec cat {} \;
